### ISSUE TITLE
Is // supported as a comment?

### ISSUE THREAD

**Issue by ketzacoatl** [b4b4r07/vim-hcl#6]
While using this plugin (along with `terraform-vim`), I found that `//` in my `.tf` files were not recognized as comments. When I dropped this plugin, `//` were properly highlighted. Should `//` be supported as a comment in this HCL plugin?

I considered making a PR based on https://github.com/hashivim/vim-terraform/blob/master/syntax/terraform.vim#L542, but I'm not familiar enough with vim plugins to decode https://github.com/b4b4r07/vim-hcl/blob/master/syntax/hcl.vim#L8.

**Comment by babarot** [comment]
@ketzacoatl Sorry for the delay in responding. I just supported // as a comment

**Comment by ketzacoatl** [comment]
sounds great! I'll upgrade and test. TY!
